version: '3'

services:
  nginx:
    image: nginx:1.16
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/media
    environment:
      - TZ="Asia/Tokyo"
    links:
      - sphinx

  sphinx:
    build: ./docker/sphinx
    volumes:
      - .:/media
