version: '3'
services:
  nginx:
    ports: 
      - 17880:80
    networks:
      app_net:
        ipv4_address: 172.16.0.2

  sphinx:
    ports:
      - 17800:8000
    networks:
      app_net:
        ipv4_address: 172.16.0.4

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
